# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/116vRGg2ozWrtkffvpmpTHrYJBMfYi-FM
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
file_path = '/content/climate_change_dataset.csv'
data = pd.read_csv(file_path)

# Compute Summary Statistics
summary_stats = data.describe()
summary_stats.to_csv('summary_statistics.csv')  # Save summary stats for reference

# Create Plots
# 1. Line plot: Average Temperature over years for a selected country (e.g., USA)
usa_data = data[data['Country'] == 'USA']
plt.figure(figsize=(10, 6))
plt.plot(usa_data['Year'], usa_data['Avg Temperature (°C)'], marker='o', linestyle='-', label='Avg Temp (°C)')
plt.title('Average Temperature Over Years (USA)', fontsize=14)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Average Temperature (°C)', fontsize=12)
plt.grid(True)
plt.legend()
plt.savefig('line_plot_avg_temp.png')
plt.close()

# 2. Bar plot: CO2 Emissions comparison across countries in a specific year (e.g., 2019)
data_2019 = data[data['Year'] == 2019]
plt.figure(figsize=(12, 6))
sns.barplot(x='Country', y='CO2 Emissions (Tons/Capita)', data=data_2019, palette='viridis')
plt.title('CO2 Emissions (2019)', fontsize=14)
plt.xlabel('Country', fontsize=12)
plt.ylabel('CO2 Emissions (Tons/Capita)', fontsize=12)
plt.xticks(rotation=45)
plt.savefig('bar_plot_co2_emissions.png')
plt.close()

# 3. Scatter plot: Relationship between Renewable Energy (%) and CO2 Emissions
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Renewable Energy (%)', y='CO2 Emissions (Tons/Capita)', hue='Country', data=data, palette='deep', s=100)
plt.title('Renewable Energy vs CO2 Emissions', fontsize=14)
plt.xlabel('Renewable Energy (%)', fontsize=12)
plt.ylabel('CO2 Emissions (Tons/Capita)', fontsize=12)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True)
plt.savefig('scatter_plot_renewable_vs_co2.png')
plt.close()

# Generate Summary Table
# Aggregating data for mean statistics by country
summary_table = data.groupby('Country').agg({
    'Avg Temperature (°C)': 'mean',
    'CO2 Emissions (Tons/Capita)': 'mean',
    'Renewable Energy (%)': 'mean',
    'Forest Area (%)': 'mean'
}).reset_index()
summary_table.columns = ['Country', 'Avg Temp (°C)', 'Avg CO2 Emissions (Tons/Capita)', 'Avg Renewable Energy (%)', 'Avg Forest Area (%)']
summary_table.to_csv('summary_table.csv', index=False)

# Save Outputs
print("Plots and summary table have been generated:")
print("- Line plot saved as line_plot_avg_temp.png")
print("- Bar plot saved as bar_plot_co2_emissions.png")
print("- Scatter plot saved as scatter_plot_renewable_vs_co2.png")
print("- Summary table saved as summary_table.csv")
print("- Summary statistics saved as summary_statistics.csv")